global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spark"
    static_configs:
      - targets:
          - "host.docker.internal:4040"

  - job_name: "gold_pipeline"
    static_configs:
      - targets:
          - "host.docker.internal:8000"

